default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: clouds4

test:
  <<: *default
  database: clouds4_test

production:
  <<: *default
  database: clouds4_production
  username: clouds4
  password: <%= ENV['CLOUDS4_DATABASE_PASSWORD'] %>
